public class STRGS {
static String defaultText = """
Testing the available mirrors:
[*] (10) https://packages-cf.termux.dev/apt/termux-main: ok
Picking mirror: (2) /data/data/com.termux/files/usr/etc/termux/mirrors/default
Get:1 https://packages-cf.termux.dev/apt/termux-main stable InRelease [14.0 kB]
Get:2 https://packages-cf.termux.dev/apt/termux-root root InRelease [14.2 kB]
Get:3 https://packages-cf.termux.dev/apt/termux-x11 x11 InRelease [14.0 kB]
Get:4 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 Packages [536 kB]
Get:5 https://packages-cf.termux.dev/apt/termux-root root/stable aarch64 Packages [20.4 kB]
Get:6 https://packages-cf.termux.dev/apt/termux-x11 x11/main aarch64 Packages [156 kB]
Fetched 755 kB in 6s (135 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
25 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  abseil-cpp alsa-lib ffmpeg fftw game-music-emu hunspell
  hunspell-en-us imlib2 jack jack2
  libandroid-sysv-semaphore libaom libarchive libass
  libbluray libcaca libdav1d libde265 libflac libgd
  libheif libid3tag libjxl libltdl liblua52 libmp3lame
  libogg libopencore-amr libopenmpt libopus libplacebo
  librav1e libsamplerate libsixel libsndfile libsoxr
  libsrt libssh libtheora libuchardet libudfread libv4l
  libvidstab libvmaf libvo-amrwbenc libvorbis libvpx
  libwebp libwebrtc-audio-processing libx264 libx265
  libzimg littlecms mpg123 mpv ocl-icd openal-soft
  openjpeg pulseaudio rlwrap rubberband speexdsp svt-av1
  xvidcore
The following NEW packages will be installed:
  abseil-cpp alsa-lib ffmpeg fftw game-music-emu hunspell
  hunspell-en-us imlib2 jack jack2
  libandroid-sysv-semaphore libaom libarchive libass
  libbluray libcaca libdav1d libde265 libflac libgd
  libheif libid3tag libjxl libltdl liblua52 libmp3lame
  libogg libopencore-amr libopenmpt libopus libplacebo
  librav1e libsamplerate libsixel libsndfile libsoxr
  libsrt libssh libtheora libuchardet libudfread libv4l
  libvidstab libvmaf libvo-amrwbenc libvorbis libvpx
  libwebp libwebrtc-audio-processing libx264 libx265
  libzimg littlecms mpg123 mpv ocl-icd openal-soft
  openjpeg pulseaudio rlwrap rubberband speexdsp svt-av1
  translate-shell xvidcore
0 upgraded, 65 newly installed, 0 to remove and 25 not upgraded.
Need to get 31.8 MB of archives.
After this operation, 128 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 abseil-cpp aarch64 20240116.2-1 [1065 kB]
Get:2 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libandroid-sysv-semaphore aarch64 0.1 [3664 B]
Get:3 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 alsa-lib aarch64 1.2.13 [438 kB]
Get:4 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 game-music-emu aarch64 0.6.3-1 [124 kB]
Get:5 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libaom aarch64 3.12.0 [1926 kB]
Get:6 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libass aarch64 0.17.3 [86.1 kB]
Get:7 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libudfread aarch64 1.1.2 [14.4 kB]
Get:8 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libbluray aarch64 1.3.4-1 [107 kB]
Get:9 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libdav1d aarch64 1.5.1 [291 kB]
Get:10 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libmp3lame aarch64 3.100-6 [115 kB]
Get:11 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libopencore-amr aarch64 0.1.6 [111 kB]
Get:12 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libogg aarch64 1.3.5 [188 kB]
Get:13 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libflac aarch64 1.4.3 [176 kB]
Get:14 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libopus aarch64 1.5.2 [186 kB]
Get:15 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libvorbis aarch64 1.3.7-2 [262 kB]
Get:16 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libsndfile aarch64 1.2.2-1 [217 kB]
Get:17 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libltdl aarch64 2.5.4 [18.0 kB]
Get:18 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libsoxr aarch64 0.1.3-7 [283 kB]
Get:19 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libwebrtc-audio-processing aarch64 1.3-1 [416 kB]
Get:20 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 speexdsp aarch64 1.2.1 [37.1 kB]
Get:21 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 pulseaudio aarch64 17.0-1 [844 kB]
Get:22 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 mpg123 aarch64 1.32.10 [263 kB]
Get:23 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libopenmpt aarch64 0.7.13 [576 kB]
Get:24 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 librav1e aarch64 0.7.1-2 [658 kB]
Get:25 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libsrt aarch64 1.5.4 [269 kB]
Get:26 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libssh aarch64 0.11.1 [205 kB]
Get:27 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libtheora aarch64 1.1.1-1 [139 kB]
Get:28 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libv4l aarch64 1.24.1-1 [94.6 kB]
Get:29 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libvidstab aarch64 1.1.1-1 [260 kB]
Get:30 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libvmaf aarch64 3.0.0 [161 kB]
Get:31 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libvo-amrwbenc aarch64 0.1.3 [52.8 kB]
Get:32 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libvpx aarch64 1:1.15.0-1 [848 kB]
Get:33 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libwebp aarch64 1.5.0 [222 kB]
Get:34 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libx264 aarch64 1:0.164.3191 [396 kB]
Get:35 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libx265 aarch64 4.1 [706 kB]
Get:36 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libzimg aarch64 3.0.5 [135 kB]
Get:37 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 littlecms aarch64 2.17 [142 kB]
Get:38 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 ocl-icd aarch64 2.3.2 [87.7 kB]
Get:39 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 fftw aarch64 3.3.10-3 [947 kB]
Get:40 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libsamplerate aarch64 0.2.2-1 [973 kB]
Get:41 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 rubberband aarch64 4.0.0 [208 kB]
Get:42 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 svt-av1 aarch64 2.3.0 [1289 kB]
Get:43 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 xvidcore aarch64 1.3.7 [127 kB]
Get:44 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 ffmpeg aarch64 7.1-4 [9846 kB]
Get:45 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 hunspell-en-us all 20240129 [162 kB]
Get:46 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 hunspell aarch64 1.7.2 [241 kB]
Get:47 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libde265 aarch64 1.0.15 [152 kB]
Get:48 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libheif aarch64 1.19.5-1 [369 kB]
Get:49 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libid3tag aarch64 0.16.3 [29.8 kB]
Get:50 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libjxl aarch64 0.11.1 [1184 kB]
Get:51 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 openjpeg aarch64 2.5.3 [151 kB]
Get:52 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 imlib2 aarch64 1.12.3-1 [508 kB]
Get:53 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 jack2 aarch64 1.9.22-1 [374 kB]
Get:54 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 jack all 0.0.1 [696 B]
Get:55 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libarchive aarch64 3.7.7 [386 kB]
Get:56 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libcaca aarch64 0.99.beta20-1 [247 kB]
Get:57 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libgd aarch64 1:2.3.3-4 [125 kB]
Get:58 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 liblua52 aarch64 5.2.4-8 [74.7 kB]
Get:59 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libplacebo aarch64 6.338.2-1 [399 kB]
Get:60 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libsixel aarch64 1.10.5 [95.8 kB]
Get:61 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 libuchardet aarch64 0.0.8 [98.8 kB]
Get:62 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 openal-soft aarch64 1.24.2 [566 kB]
Get:63 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 mpv aarch64 0.39.0-1 [994 kB]
Get:64 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 rlwrap aarch64 0.46.1 [95.4 kB]
Get:65 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 translate-shell all 0.9.7.1 [46.0 kB]
Fetched 31.8 MB in 9s (3680 kB/s)
Selecting previously unselected package abseil-cpp.
(Reading database ... 32577 files and directories currently installed.)
Preparing to unpack .../00-abseil-cpp_20240116.2-1_aarch64.deb ...
Unpacking abseil-cpp (20240116.2-1) ...
Selecting previously unselected package libandroid-sysv-semaphore.
Preparing to unpack .../01-libandroid-sysv-semaphore_0.1_aarch64.deb ...
Unpacking libandroid-sysv-semaphore (0.1) ...
Selecting previously unselected package alsa-lib.
Preparing to unpack .../02-alsa-lib_1.2.13_aarch64.deb ...
Unpacking alsa-lib (1.2.13) ...
Selecting previously unselected package game-music-emu.
Preparing to unpack .../03-game-music-emu_0.6.3-1_aarch64.deb ...
Unpacking game-music-emu (0.6.3-1) ...
Selecting previously unselected package libaom.
Preparing to unpack .../04-libaom_3.12.0_aarch64.deb ...
Unpacking libaom (3.12.0) ...
Selecting previously unselected package libass.
Preparing to unpack .../05-libass_0.17.3_aarch64.deb ...
Unpacking libass (0.17.3) ...
Selecting previously unselected package libudfread.
Preparing to unpack .../06-libudfread_1.1.2_aarch64.deb ...
Unpacking libudfread (1.1.2) ...
Selecting previously unselected package libbluray.
Preparing to unpack .../07-libbluray_1.3.4-1_aarch64.deb ...
Unpacking libbluray (1.3.4-1) ...
Selecting previously unselected package libdav1d.
Preparing to unpack .../08-libdav1d_1.5.1_aarch64.deb ...
Unpacking libdav1d (1.5.1) ...
Selecting previously unselected package libmp3lame.
Preparing to unpack .../09-libmp3lame_3.100-6_aarch64.deb ...
Unpacking libmp3lame (3.100-6) ...
Selecting previously unselected package libopencore-amr.
Preparing to unpack .../10-libopencore-amr_0.1.6_aarch64.deb ...
Unpacking libopencore-amr (0.1.6) ...
Selecting previously unselected package libogg.
Preparing to unpack .../11-libogg_1.3.5_aarch64.deb ...
Unpacking libogg (1.3.5) ...
Selecting previously unselected package libflac.
Preparing to unpack .../12-libflac_1.4.3_aarch64.deb ...
Unpacking libflac (1.4.3) ...
Selecting previously unselected package libopus.
Preparing to unpack .../13-libopus_1.5.2_aarch64.deb ...
Unpacking libopus (1.5.2) ...
Selecting previously unselected package libvorbis.
Preparing to unpack .../14-libvorbis_1.3.7-2_aarch64.deb ...
Unpacking libvorbis (1.3.7-2) ...
Selecting previously unselected package libsndfile.
Preparing to unpack .../15-libsndfile_1.2.2-1_aarch64.deb ...
Unpacking libsndfile (1.2.2-1) ...
Selecting previously unselected package libltdl.
Preparing to unpack .../16-libltdl_2.5.4_aarch64.deb ...
Unpacking libltdl (2.5.4) ...
Selecting previously unselected package libsoxr.
Preparing to unpack .../17-libsoxr_0.1.3-7_aarch64.deb ...
Unpacking libsoxr (0.1.3-7) ...
Selecting previously unselected package libwebrtc-audio-processing.
Preparing to unpack .../18-libwebrtc-audio-processing_1.3-1_aarch64.deb ...
Unpacking libwebrtc-audio-processing (1.3-1) ...
Selecting previously unselected package speexdsp.
Preparing to unpack .../19-speexdsp_1.2.1_aarch64.deb ...
Unpacking speexdsp (1.2.1) ...
Selecting previously unselected package pulseaudio.
Preparing to unpack .../20-pulseaudio_17.0-1_aarch64.deb ...
Unpacking pulseaudio (17.0-1) ...
Selecting previously unselected package mpg123.
Preparing to unpack .../21-mpg123_1.32.10_aarch64.deb ...
Unpacking mpg123 (1.32.10) ...
Selecting previously unselected package libopenmpt.
Preparing to unpack .../22-libopenmpt_0.7.13_aarch64.deb ...
Unpacking libopenmpt (0.7.13) ...
Selecting previously unselected package librav1e.
Preparing to unpack .../23-librav1e_0.7.1-2_aarch64.deb ...
Unpacking librav1e (0.7.1-2) ...
Selecting previously unselected package libsrt.
Preparing to unpack .../24-libsrt_1.5.4_aarch64.deb ...
Unpacking libsrt (1.5.4) ...
Selecting previously unselected package libssh.
Preparing to unpack .../25-libssh_0.11.1_aarch64.deb ...
Unpacking libssh (0.11.1) ...
Selecting previously unselected package libtheora.
Preparing to unpack .../26-libtheora_1.1.1-1_aarch64.deb ...
Unpacking libtheora (1.1.1-1) ...
Selecting previously unselected package libv4l.
Preparing to unpack .../27-libv4l_1.24.1-1_aarch64.deb ...
Unpacking libv4l (1.24.1-1) ...
Selecting previously unselected package libvidstab.
Preparing to unpack .../28-libvidstab_1.1.1-1_aarch64.deb ...
Unpacking libvidstab (1.1.1-1) ...
Selecting previously unselected package libvmaf.
Preparing to unpack .../29-libvmaf_3.0.0_aarch64.deb ...
Unpacking libvmaf (3.0.0) ...
Selecting previously unselected package libvo-amrwbenc.
Preparing to unpack .../30-libvo-amrwbenc_0.1.3_aarch64.deb ...
Unpacking libvo-amrwbenc (0.1.3) ...
Selecting previously unselected package libvpx.
Preparing to unpack .../31-libvpx_1%3a1.15.0-1_aarch64.deb ...
Unpacking libvpx (1:1.15.0-1) ...
Selecting previously unselected package libwebp.
Preparing to unpack .../32-libwebp_1.5.0_aarch64.deb ...
Unpacking libwebp (1.5.0) ...
Selecting previously unselected package libx264.
Preparing to unpack .../33-libx264_1%3a0.164.3191_aarch64.deb ...
Unpacking libx264 (1:0.164.3191) ...
Selecting previously unselected package libx265.
Preparing to unpack .../34-libx265_4.1_aarch64.deb ...
Unpacking libx265 (4.1) ...
Selecting previously unselected package libzimg.
Preparing to unpack .../35-libzimg_3.0.5_aarch64.deb ...
Unpacking libzimg (3.0.5) ...
Selecting previously unselected package littlecms.
Preparing to unpack .../36-littlecms_2.17_aarch64.deb ...
Unpacking littlecms (2.17) ...
Selecting previously unselected package ocl-icd.
Preparing to unpack .../37-ocl-icd_2.3.2_aarch64.deb ...
Unpacking ocl-icd (2.3.2) ...
Selecting previously unselected package fftw.
Preparing to unpack .../38-fftw_3.3.10-3_aarch64.deb ...
Unpacking fftw (3.3.10-3) ...
Selecting previously unselected package libsamplerate.
Preparing to unpack .../39-libsamplerate_0.2.2-1_aarch64.deb ...
Unpacking libsamplerate (0.2.2-1) ...
Selecting previously unselected package rubberband.
Preparing to unpack .../40-rubberband_4.0.0_aarch64.deb ...
Unpacking rubberband (4.0.0) ...
Selecting previously unselected package svt-av1.
Preparing to unpack .../41-svt-av1_2.3.0_aarch64.deb ...
Unpacking svt-av1 (2.3.0) ...
Selecting previously unselected package xvidcore.
Preparing to unpack .../42-xvidcore_1.3.7_aarch64.deb ...
Unpacking xvidcore (1.3.7) ...
Selecting previously unselected package ffmpeg.
Preparing to unpack .../43-ffmpeg_7.1-4_aarch64.deb ...
Unpacking ffmpeg (7.1-4) ...
Selecting previously unselected package hunspell-en-us.
Preparing to unpack .../44-hunspell-en-us_20240129_all.deb ...
Unpacking hunspell-en-us (20240129) ...
Selecting previously unselected package hunspell.
Preparing to unpack .../45-hunspell_1.7.2_aarch64.deb ...
Unpacking hunspell (1.7.2) ...
Selecting previously unselected package libde265.
Preparing to unpack .../46-libde265_1.0.15_aarch64.deb ...
Unpacking libde265 (1.0.15) ...
Selecting previously unselected package libheif.
Preparing to unpack .../47-libheif_1.19.5-1_aarch64.deb ...
Unpacking libheif (1.19.5-1) ...
Selecting previously unselected package libid3tag.
Preparing to unpack .../48-libid3tag_0.16.3_aarch64.deb ...
Unpacking libid3tag (0.16.3) ...
Selecting previously unselected package libjxl.
Preparing to unpack .../49-libjxl_0.11.1_aarch64.deb ...
Unpacking libjxl (0.11.1) ...
Selecting previously unselected package openjpeg.
Preparing to unpack .../50-openjpeg_2.5.3_aarch64.deb ...
Unpacking openjpeg (2.5.3) ...
Selecting previously unselected package imlib2.
Preparing to unpack .../51-imlib2_1.12.3-1_aarch64.deb ...
Unpacking imlib2 (1.12.3-1) ...
Selecting previously unselected package jack2.
Preparing to unpack .../52-jack2_1.9.22-1_aarch64.deb ...
Unpacking jack2 (1.9.22-1) ...
Selecting previously unselected package jack.
Preparing to unpack .../53-jack_0.0.1_all.deb ...
Unpacking jack (0.0.1) ...
Selecting previously unselected package libarchive.
Preparing to unpack .../54-libarchive_3.7.7_aarch64.deb ...
Unpacking libarchive (3.7.7) ...
Selecting previously unselected package libcaca.
Preparing to unpack .../55-libcaca_0.99.beta20-1_aarch64.deb ...
Unpacking libcaca (0.99.beta20-1) ...
Selecting previously unselected package libgd.
Preparing to unpack .../56-libgd_1%3a2.3.3-4_aarch64.deb ...
Unpacking libgd (1:2.3.3-4) ...
Selecting previously unselected package liblua52.
Preparing to unpack .../57-liblua52_5.2.4-8_aarch64.deb ...
Unpacking liblua52 (5.2.4-8) ...
Selecting previously unselected package libplacebo.
Preparing to unpack .../58-libplacebo_6.338.2-1_aarch64.deb ...
Unpacking libplacebo (6.338.2-1) ...
Selecting previously unselected package libsixel.
Preparing to unpack .../59-libsixel_1.10.5_aarch64.deb ...
Unpacking libsixel (1.10.5) ...
Selecting previously unselected package libuchardet.
Preparing to unpack .../60-libuchardet_0.0.8_aarch64.deb ...
Unpacking libuchardet (0.0.8) ...
Selecting previously unselected package openal-soft.
Preparing to unpack .../61-openal-soft_1.24.2_aarch64.deb ...
Unpacking openal-soft (1.24.2) ...
Selecting previously unselected package mpv.
Preparing to unpack .../62-mpv_0.39.0-1_aarch64.deb ...
Unpacking mpv (0.39.0-1) ...
Selecting previously unselected package rlwrap.
Preparing to unpack .../63-rlwrap_0.46.1_aarch64.deb ...
Unpacking rlwrap (0.46.1) ...
Selecting previously unselected package translate-shell.
Preparing to unpack .../64-translate-shell_0.9.7.1_all.deb ...
Unpacking translate-shell (0.9.7.1) ...
Setting up libv4l (1.24.1-1) ...
Setting up libopus (1.5.2) ...
Setting up svt-av1 (2.3.0) ...
Setting up libssh (0.11.1) ...
Setting up littlecms (2.17) ...
Setting up libvpx (1:1.15.0-1) ...
Setting up libudfread (1.1.2) ...
Setting up libsoxr (0.1.3-7) ...
Setting up libvmaf (3.0.0) ...
Setting up libogg (1.3.5) ...
Setting up speexdsp (1.2.1) ...
Setting up libjxl (0.11.1) ...
Setting up libarchive (3.7.7) ...
Setting up libsamplerate (0.2.2-1) ...
Setting up fftw (3.3.10-3) ...
Setting up libaom (3.12.0) ...
Setting up libvorbis (1.3.7-2) ...
Setting up libvo-amrwbenc (0.1.3) ...
Setting up libde265 (1.0.15) ...
Setting up openal-soft (1.24.2) ...
Setting up xvidcore (1.3.7) ...
Setting up libtheora (1.1.1-1) ...
Setting up libltdl (2.5.4) ...
Setting up libbluray (1.3.4-1) ...
Setting up rlwrap (0.46.1) ...
Setting up libandroid-sysv-semaphore (0.1) ...
Setting up libuchardet (0.0.8) ...
Setting up libdav1d (1.5.1) ...
Setting up game-music-emu (0.6.3-1) ...
Setting up ocl-icd (2.3.2) ...
Setting up libass (0.17.3) ...
Setting up libmp3lame (3.100-6) ...
Setting up librav1e (0.7.1-2) ...
Setting up liblua52 (5.2.4-8) ...
Setting up libx264 (1:0.164.3191) ...
Setting up hunspell-en-us (20240129) ...
Setting up libvidstab (1.1.1-1) ...
Setting up libx265 (4.1) ...
Setting up libzimg (3.0.5) ...
Setting up libid3tag (0.16.3) ...
Setting up libflac (1.4.3) ...
Setting up libopencore-amr (0.1.6) ...
Setting up libplacebo (6.338.2-1) ...
Setting up abseil-cpp (20240116.2-1) ...
Setting up openjpeg (2.5.3) ...
Setting up libwebp (1.5.0) ...
Setting up libsrt (1.5.4) ...
Setting up alsa-lib (1.2.13) ...
Setting up translate-shell (0.9.7.1) ...
Setting up hunspell (1.7.2) ...
Setting up libheif (1.19.5-1) ...
Setting up libgd (1:2.3.3-4) ...
Setting up imlib2 (1.12.3-1) ...
Setting up libcaca (0.99.beta20-1) ...
Setting up libsndfile (1.2.2-1) ...
Setting up libwebrtc-audio-processing (1.3-1) ...
Setting up rubberband (4.0.0) ...
Setting up jack2 (1.9.22-1) ...
Setting up libsixel (1.10.5) ...
Setting up pulseaudio (17.0-1) ...
Setting up mpg123 (1.32.10) ...
Setting up jack (0.0.1) ...
Setting up libopenmpt (0.7.13) ...
Setting up ffmpeg (7.1-4) ...
Setting up mpv (0.39.0-1) ...
Processing triggers for update-info-dir (7.2) ...
Processing triggers for gdk-pixbuf (2.42.12) ..
              """;
    public static void main(String[] args) {
        if(args.length < 1) {
            smPrint(defaultText, 1, false);
        }
        else if(args.length == 1) {
            smPrint(args[0], 1, false);
        }
        else if(args.length == 2) {
            int intArgs = Integer.parseInt(args[1]);
            if(args[0].equals("default")) {
                smPrint(defaultText, intArgs, false);
            }
            else {
                smPrint(args[0], intArgs, false);
            }
        }
        else if(args.length == 3) {
            int intArgs = Integer.parseInt(args[1]);
            boolean green = Boolean.parseBoolean(args[2]);
            if(args[0].equals("default")) {
                smPrint(defaultText, intArgs, false);
            }
            else {
                smPrint(args[0], intArgs, false);
            }
        }
        else {System.out.println("Error");}
    }
	public static void smPrint(String text, int time, boolean green) {
	    char ch;
	    if(green) {
	        String color = "\u001B[32m";
	    }
	    else {
	        String color = "";
	    }
        for (int i = 0; i < text.length(); i++) {
            ch = text.charAt(i);
            System.out.print(color + ch);
            try {Thread.sleep(time);}
            catch (InterruptedException e) {e.printStackTrace();}
        }
        System.out.println("");
    }
}